name: Create Production Builds

on:
  push:
    branches:
      - agentic-experiment

jobs:
  build_android:
    type: build # This job type creates a production build for Android
    params:
      platform: android
      profile: development
