import { createContext, use, useEffect, useMemo, type ReactNode } from 'react';

import { useFinanceState } from '@/providers/finance-provider';

export type AppLanguage = 'en' | 'he';

export const APP_LANGUAGE_OPTIONS = [
  { value: 'en-US', label: 'English' },
  { value: 'he-IL', label: 'Hebrew' },
] as const;

const HEBREW: Record<string, string> = {
  English: 'אנגלית', Hebrew: 'עברית',
  Overview: 'סקירה', Transactions: 'תנועות', Plan: 'תכנון', More: 'עוד',
  Transaction: 'תנועה', Budget: 'תקציב', Goal: 'יעד', Account: 'חשבון', Category: 'קטגוריה',
  'Recurring transaction': 'תנועה מחזורית', 'Exchange rate': 'שער חליפין', Appearance: 'מראה',
  'Import & export': 'ייבוא וייצוא',
  'Money, made calmer.': 'כסף, בצורה רגועה יותר.',
  'Qashy is a private, local-first place for everyday spending, flexible budgets, and goals.': 'Qashy הוא מקום פרטי ומקומי לניהול הוצאות יומיומיות, תקציבים גמישים ויעדים.',
  'Private by default': 'פרטי כברירת מחדל',
  'No account and no finance data leaves this device.': 'ללא חשבון, ושום מידע פיננסי לא יוצא מהמכשיר.',
  'Flexible, not fussy': 'גמיש, בלי טרחה',
  'Track the categories and time periods that fit your life.': 'עקבו אחר הקטגוריות ותקופות הזמן שמתאימות לחיים שלכם.',
  'Ready everywhere': 'מוכן בכל מקום',
  'A native-feeling phone app and a responsive desktop PWA.': 'אפליקציה טבעית לטלפון ויישום רספונסיבי למחשב.',
  'Language and currency': 'שפה ומטבע',
  'Dates and amounts will follow these preferences.': 'התאריכים, המספרים והממשק יתאימו לבחירות שלכם.',
  'Create your first account': 'צרו את החשבון הראשון שלכם',
  'Balances are derived from this opening amount and your transactions.': 'היתרות מחושבות מסכום הפתיחה ומהתנועות שלכם.',
  'Make it yours': 'התאימו לטעמכם',
  'Follow the system or choose an accent that feels like you.': 'השתמשו בהגדרת המערכת או בחרו צבע שמתאים לכם.',
  Language: 'שפה', 'Base currency': 'מטבע בסיס',
  'Budgets, goals, and reports use this currency.': 'תקציבים, יעדים ודוחות משתמשים במטבע הזה.',
  'Search by currency name or code': 'חיפוש לפי שם מטבע או קוד',
  'Account name': 'שם החשבון', Everyday: 'יומיומי', 'Account type': 'סוג חשבון', Type: 'סוג',
  Checking: 'עו״ש', Cash: 'מזומן', Savings: 'חיסכון', Credit: 'אשראי', Wallet: 'ארנק',
  checking: 'עו״ש', cash: 'מזומן', savings: 'חיסכון', credit: 'אשראי', wallet: 'ארנק',
  'Opening balance': 'יתרת פתיחה',
  System: 'מערכת', Light: 'בהיר', Dark: 'כהה', Accent: 'צבע הדגשה', 'System accent': 'צבע המערכת',
  Back: 'חזרה', Continue: 'המשך', 'Start using Qashy': 'התחילו להשתמש ב־Qashy', 'Setting up…': 'מגדיר…',
  'Choose language': 'בחירת שפה', 'Choose base currency': 'בחירת מטבע בסיס',
  'Close language choices': 'סגירת אפשרויות השפה', 'Close base currency choices': 'סגירת אפשרויות המטבע',
  'Search base currency': 'חיפוש מטבע בסיס', 'No matching choices': 'לא נמצאו אפשרויות מתאימות',
  'A quieter view of your finances.': 'מבט רגוע יותר על הכספים שלכם.',
  'YOUR MONEY AT A GLANCE': 'הכסף שלכם במבט אחד', 'CURRENT NET WORTH': 'שווי נקי נוכחי',
  Income: 'הכנסה', Spent: 'הוצאות', 'Net flow': 'תזרים נטו',
  'Spending rhythm': 'קצב ההוצאות', 'Spending by category': 'הוצאות לפי קטגוריה', 'By category': 'לפי קטגוריה',
  'Budget pulse': 'מצב התקציב', 'Open plan': 'פתיחת התכנון',
  'Over budget — review the categories driving it.': 'חריגה מהתקציב — בדקו אילו קטגוריות גורמות לכך.',
  'Create a flexible monthly or custom budget to see your pace here.': 'צרו תקציב חודשי או מותאם כדי לראות כאן את הקצב שלכם.',
  'Create budget': 'יצירת תקציב', Manage: 'ניהול', 'Coming up': 'בהמשך', Skip: 'דילוג', 'Mark paid': 'סימון כשולם',
  'Recent activity': 'פעילות אחרונה', 'See all': 'הצגת הכול', 'See all transactions': 'הצגת כל התנועות',
  'Choose another month or open the full transaction list.': 'בחרו חודש אחר או פתחו את רשימת התנועות המלאה.',
  'Add the first transaction and Qashy will turn it into useful context.': 'הוסיפו את התנועה הראשונה ו־Qashy יהפוך אותה לתמונה שימושית.',
  Upcoming: 'בקרוב', upcoming: 'בקרוב', UPCOMING: 'בקרוב', SPENT: 'הוצא',
  'Your ledger is ready': 'היומן שלכם מוכן',
  'Add your first transaction to start seeing your financial rhythm.': 'הוסיפו תנועה ראשונה כדי להתחיל לראות את התמונה הפיננסית.',
  'No spending in this period': 'אין הוצאות בתקופה הזו', 'Add an expense to start the rhythm.': 'הוסיפו הוצאה כדי להתחיל.',
  'No spending yet': 'אין עדיין הוצאות', Uncategorized: 'ללא קטגוריה', Other: 'אחר',
  'Previous month': 'החודש הקודם', 'Next month': 'החודש הבא',
  'Search, filter, and manage your local ledger.': 'חפשו, סננו ונהלו את היומן המקומי שלכם.',
  'Search transactions': 'חיפוש תנועות', 'Search title or note': 'חיפוש בכותרת או בהערה',
  All: 'הכול', Expense: 'הוצאה', Transfer: 'העברה',
  all: 'הכול', expense: 'הוצאה', income: 'הכנסה', transfer: 'העברה',
  Select: 'בחירה', 'Done selecting': 'סיום בחירה', 'Import or export': 'ייבוא או ייצוא',
  Clear: 'ניקוי', Done: 'סיום', 'Change category': 'שינוי קטגוריה',
  'Select only income or only expense transactions to assign a category.': 'בחרו רק תנועות הכנסה או רק תנועות הוצאה כדי לשייך קטגוריה.',
  'Transfers do not have categories. Select only income or expense transactions to change categories.': 'להעברות אין קטגוריות. בחרו רק תנועות הכנסה או הוצאה כדי לשנות קטגוריות.',
  'Delete selected': 'מחיקת הנבחרות', 'Choose one or more transactions below.': 'בחרו תנועה אחת או יותר למטה.',
  'Nothing matches': 'אין תוצאות מתאימות', 'No transactions yet': 'אין עדיין תנועות',
  'Try another search or filter.': 'נסו חיפוש או סינון אחר.', 'Add your first income, expense, or transfer.': 'הוסיפו הכנסה, הוצאה או העברה ראשונה.',
  'Add transaction': 'הוספת תנועה', Title: 'כותרת', Date: 'תאריך', Note: 'הערה',
  Status: 'מצב', Amount: 'סכום', Tags: 'תגיות', Notes: 'הערות', 'Destination account': 'חשבון יעד',
  'Transaction kind': 'סוג תנועה', 'Transaction tags': 'תגיות התנועה',
  'Unknown account': 'חשבון לא מוכר',
  'Transfer, money moved': 'העברה, כסף הועבר', 'Income, money in': 'הכנסה, כסף נכנס', 'Expense, money out': 'הוצאה, כסף יצא',
  plus: 'פלוס', minus: 'מינוס', into: 'אל', selected: 'נבחר', 'not selected': 'לא נבחר',
  'Select transaction': 'בחירת תנועה',
  'Long press to select this transaction for batch actions.': 'לחצו לחיצה ארוכה כדי לבחור את התנועה לפעולות מרובות.',
  'Destination amount': 'סכום יעד', 'Destination base amount (minor units)': 'סכום בסיס ביעד (יחידות משנה)',
  'What was it?': 'על מה זה היה?', 'From account': 'מחשבון', 'To account': 'לחשבון',
  'Transfers need two accounts': 'העברות דורשות שני חשבונות',
  'Add another account, then return here to finish this transfer. Your draft will stay open.': 'הוסיפו חשבון נוסף ואז חזרו לכאן כדי להשלים את ההעברה. הטיוטה תישמר.',
  'Add another account': 'הוספת חשבון נוסף',
  'Calculated from saved rates': 'מחושב משערים שמורים',
  'The destination receives the same amount; same-currency transfers always conserve value.': 'חשבון היעד מקבל את אותו הסכום; העברות באותו מטבע תמיד שומרות על הערך.',
  'Use saved effective rate': 'שימוש בשער השמור',
  'Leave blank to use the saved rate for this date. The applied rate is snapshotted.': 'השאירו ריק כדי להשתמש בשער השמור לתאריך הזה. השער שיוחל יישמר.',
  'Optional context': 'הקשר אופציונלי', 'Make this recurring instead': 'הפיכה לתנועה מחזורית',
  'Save changes': 'שמירת שינויים', 'Delete transaction': 'מחיקת תנועה', Saving: 'שומר', 'Saving…': 'שומר…',
  'Set flexible limits and track progress toward meaningful goals.': 'הגדירו גבולות גמישים ועקבו אחר התקדמות ליעדים משמעותיים.',
  Budgets: 'תקציבים', Goals: 'יעדים', Edit: 'עריכה', Open: 'פתיחה', spent: 'הוצאו', left: 'נותרו',
  'Give spending a gentle boundary': 'תנו להוצאות גבול נעים',
  'Create a monthly, weekly, yearly, or one-off budget. Nothing is forced into envelopes.': 'צרו תקציב חודשי, שבועי, שנתי או חד־פעמי. בלי לכפות שיטת מעטפות.',
  'Create a budget': 'יצירת תקציב', 'Save toward something real': 'חסכו למשהו אמיתי',
  'Track a savings target or a planned purchase with manual or linked progress.': 'עקבו אחר יעד חיסכון או רכישה מתוכננת באמצעות התקדמות ידנית או מקושרת.',
  'Create a goal': 'יצירת יעד', 'Create goal': 'יצירת יעד', Period: 'תקופה', Day: 'יום', Week: 'שבוע', Month: 'חודש', Year: 'שנה', Custom: 'מותאם',
  day: 'יום', week: 'שבוע', month: 'חודש', year: 'שנה', custom: 'מותאם',
  to: 'עד', rollover: 'העברה', by: 'עד', of: 'מתוך', required: 'חובה',
  'Budget name': 'שם התקציב', 'Total limit': 'מגבלה כוללת', 'End date': 'תאריך סיום', Rollover: 'העברה לתקופה הבאה',
  'Budget period': 'תקופת התקציב', 'Included categories': 'קטגוריות כלולות',
  'Budget progress': 'התקדמות התקציב', 'Category budget progress': 'התקדמות תקציב הקטגוריה', 'Goal progress': 'התקדמות היעד',
  'Carry both surplus and overspend forward.': 'העבירו גם עודף וגם חריגה לתקופה הבאה.',
  'Categories and caps': 'קטגוריות ומגבלות', 'Leave every category unselected to count all expenses.': 'השאירו את כל הקטגוריות לא מסומנות כדי לכלול את כל ההוצאות.',
  'No cap': 'ללא מגבלה', 'Save budget': 'שמירת תקציב', 'Delete budget': 'מחיקת תקציב',
  'Savings goal': 'יעד חיסכון', 'Planned purchase': 'רכישה מתוכננת', 'Goal name': 'שם היעד',
  'Starting progress': 'התקדמות התחלתית', 'Target date (optional)': 'תאריך יעד (אופציונלי)',
  'Automatic progress': 'התקדמות אוטומטית',
  'Optionally count matching posted transactions. You can still add progress manually.': 'אפשר לכלול תנועות תואמות שנרשמו. עדיין ניתן להוסיף התקדמות ידנית.',
  'Linked account': 'חשבון מקושר', 'Linked category': 'קטגוריה מקושרת', None: 'ללא',
  'Add a manual contribution': 'הוספת הפקדה ידנית', 'Save goal': 'שמירת יעד', 'Delete goal': 'מחיקת יעד',
  'Accounts, categories, automation, portability, and appearance.': 'חשבונות, קטגוריות, אוטומציה, ניידות ומראה.',
  Accounts: 'חשבונות', Add: 'הוספה', Categories: 'קטגוריות', Automation: 'אוטומציה',
  'New recurring': 'מחזורית חדשה', 'Exchange rates': 'שערי חליפין', 'Add rate': 'הוספת שער', Archived: 'בארכיון',
  'Subscriptions and scheduled income will appear here.': 'מינויים והכנסות מתוזמנות יופיעו כאן.',
  'Add a manual rate when you create an account in another currency.': 'הוסיפו שער ידני כשיוצרים חשבון במטבע אחר.',
  Restore: 'שחזור', 'Restoring…': 'משחזר…',
  'Theme, Material You, and accent': 'ערכת נושא, Material You וצבע הדגשה',
  'CSV portability': 'ניידות באמצעות CSV', 'Reset all data': 'איפוס כל הנתונים',
  'Delete everything and return to first-time setup': 'מחיקת הכול וחזרה להגדרה הראשונית', 'Resetting…': 'מאפס…',
  Privacy: 'פרטיות', 'Local-first · no account · no tracking': 'מקומי בלבד · ללא חשבון · ללא מעקב',
  Currency: 'מטבע', 'Changing this adjusts the derived account balance.': 'שינוי זה מעדכן את יתרת החשבון המחושבת.',
  Color: 'צבע', 'Save account': 'שמירת חשבון', 'Create account': 'יצירת חשבון', 'Archive account': 'העברת חשבון לארכיון',
  'Category name': 'שם הקטגוריה', Icon: 'סמל', 'Parent category': 'קטגוריית אב',
  'Save category': 'שמירת קטגוריה', 'Create category': 'יצירת קטגוריה', 'Archive category': 'העברת קטגוריה לארכיון',
  Repeats: 'חוזר', Every: 'כל', Starts: 'מתחיל', 'Ends (optional)': 'מסתיים (אופציונלי)',
  'Recurring transaction kind': 'סוג התנועה המחזורית', 'Recurring account': 'חשבון לתנועה מחזורית',
  'Recurring category': 'קטגוריה לתנועה מחזורית', 'Recurring tags': 'תגיות לתנועה מחזורית',
  'Recurrence period': 'תקופת החזרה', 'Schedule active': 'תזמון פעיל',
  'Pause without deleting this schedule.': 'השהו מבלי למחוק את התזמון.',
  'Post automatically': 'רישום אוטומטי',
  'Off by default. Upcoming items wait for your review.': 'כבוי כברירת מחדל. תנועות עתידיות ממתינות לבדיקה שלכם.',
  Active: 'פעיל', Paused: 'מושהה', Ended: 'הסתיים', Monthly: 'חודשי',
  'Save schedule': 'שמירת תזמון', 'Create schedule': 'יצירת תזמון', 'Delete schedule': 'מחיקת תזמון',
  'Accent source': 'מקור צבע ההדגשה', 'Qashy default': 'ברירת המחדל של Qashy', 'Material You wallpaper': 'טפט Material You',
  'Android 12 and later derive this from your wallpaper. Older versions use Qashy’s default palette.': 'ב־Android 12 ומעלה הצבע נגזר מהטפט. גרסאות ישנות משתמשות בצבעי ברירת המחדל של Qashy.',
  'Uses Qashy’s indigo accent on neutral surfaces.': 'משתמש בצבע האינדיגו של Qashy על משטחים ניטרליים.',
  'Curated accents': 'צבעים נבחרים', 'Custom accent': 'צבע מותאם', PREVIEW: 'תצוגה מקדימה',
  'Only the accent changes. Qashy gently adjusts unsafe colors to preserve contrast.': 'רק צבע ההדגשה משתנה. Qashy מתאים בעדינות צבעים בעייתיים כדי לשמור על ניגודיות.',
  'Color, contrast, and clarity': 'צבע, ניגודיות ובהירות',
  'Qashy adapts the same hierarchy across iOS, Android, and desktop.': 'Qashy מתאים את אותה היררכיה ל־iOS, ל־Android ולמחשב.',
  'Save appearance': 'שמירת מראה', Saved: 'נשמר',
  'Export transactions': 'ייצוא תנועות', 'Export CSV': 'ייצוא CSV', 'Import transactions': 'ייבוא תנועות',
  'Creates a UTF-8 CSV with dates, statuses, amounts, currencies, source and destination accounts, categories, tags, notes, exchange-rate snapshots, and transfer linkage.': 'יוצר קובץ CSV בקידוד UTF-8 עם תאריכים, מצבים, סכומים, מטבעות, חשבונות מקור ויעד, קטגוריות, תגיות, הערות, שערי חליפין וקישורי העברות.',
  'Headers are matched automatically. Required columns are date, type, title, amount, currency, and account. Nothing is committed until after preview.': 'הכותרות מותאמות אוטומטית. העמודות הנדרשות הן תאריך, סוג, כותרת, סכום, מטבע וחשבון. דבר לא נשמר לפני התצוגה המקדימה.',
  'Choose CSV': 'בחירת CSV', 'Column mapping': 'מיפוי עמודות', Required: 'חובה', 'Not mapped': 'לא ממופה',
  'Choose the source column for each Qashy field. Optional fields can stay Not mapped.': 'בחרו את עמודת המקור לכל שדה ב־Qashy. שדות אופציונליים יכולים להישאר לא ממופים.',
  'Default account': 'חשבון ברירת מחדל', 'Default category': 'קטגוריית ברירת מחדל',
  'The default category is used only for rows with the same transaction type. Other rows stay uncategorized.': 'קטגוריית ברירת המחדל משמשת רק שורות מאותו סוג תנועה. שורות אחרות נשארות ללא קטגוריה.',
  'Preview import': 'תצוגה מקדימה לייבוא', Ready: 'מוכן', Duplicates: 'כפילויות', Rejected: 'נדחו',
  'From currency': 'ממטבע', 'Effective date': 'תאריך תחולה', 'Save rate': 'שמירת שער', 'Delete rate': 'מחיקת שער',
  'Try again.': 'נסו שוב.', 'Try again': 'נסו שוב', 'Check the form and try again.': 'בדקו את הטופס ונסו שוב.',
  Target: 'יעד', Contribution: 'הפקדה', 'Contribution date': 'תאריך ההפקדה',
  'Contribution amount': 'סכום ההפקדה', 'Contribution note': 'הערת הפקדה',
  'Start date': 'תאריך התחלה', 'Target date': 'תאריך יעד', 'Repeat interval': 'מרווח חזרה',
  'Category cap': 'מגבלת קטגוריה', 'Budget limit': 'מגבלת תקציב', 'Recurring amount': 'סכום מחזורי',
  'Destination base amount': 'סכום בסיס ביעד', Value: 'ערך', 'cap (optional)': 'מגבלה (אופציונלי)',
  'Manual contribution': 'הפקדה ידנית', 'Manual contributions': 'הפקדות ידניות',
  'No manual contributions yet.': 'אין עדיין הפקדות ידניות.',
  'Save contribution': 'שמירת הפקדה', 'Add contribution': 'הוספת הפקדה',
  'A category with child categories must stay at the top level.': 'קטגוריה שיש לה קטגוריות משנה חייבת להישאר ברמה העליונה.',
  'Use a valid locale such as en-US.': 'השתמשו בהגדרת אזור תקינה, למשל he-IL.',
  'Use a three-letter currency code such as USD.': 'השתמשו בקוד מטבע בן שלוש אותיות, למשל ILS.',
  'Use a supported ISO 4217 currency code.': 'השתמשו בקוד מטבע נתמך מתקן ISO 4217.',
  'Enter a valid number.': 'הזינו מספר תקין.', 'Enter a valid amount.': 'הזינו סכום תקין.',
  'Amount is outside the supported range.': 'הסכום מחוץ לטווח הנתמך.',
  'Converted amount is outside the supported range.': 'הסכום שהומר מחוץ לטווח הנתמך.',
  'Exchange rate must be a positive number.': 'שער החליפין חייב להיות מספר חיובי.',
  'Use a six-digit hex color such as #5966E9.': 'השתמשו בצבע הקסדצימלי בן שש ספרות, למשל #5966E9.',
  'Use a real date in YYYY-MM-DD format.': 'השתמשו בתאריך אמיתי בתבנית YYYY-MM-DD.',
  'Choose a destination account.': 'בחרו חשבון יעד.',
  'Currency is locked because this account has transaction or schedule history.': 'המטבע נעול משום שלחשבון הזה יש היסטוריית תנועות או תזמונים.',
  'End date must not precede the start date.': 'תאריך הסיום אינו יכול להיות לפני תאריך ההתחלה.',
  'End date must not precede the budget start date.': 'תאריך הסיום אינו יכול להיות לפני תאריך תחילת התקציב.',
  'Qashy setup is already complete.': 'הגדרת Qashy כבר הושלמה.',
  'Choose a valid account type.': 'בחרו סוג חשבון תקין.', 'Choose a valid theme mode.': 'בחרו מצב ערכת נושא תקין.',
  'Choose a valid accent source.': 'בחרו מקור צבע הדגשה תקין.',
  'Base currency cannot change after setup is complete.': 'לא ניתן לשנות את מטבע הבסיס לאחר השלמת ההגדרה.',
  'Account currency cannot change after transactions or schedules reference it.': 'לא ניתן לשנות את מטבע החשבון לאחר שתנועות או תזמונים מפנים אליו.',
  'Choose a valid category kind.': 'בחרו סוג קטגוריה תקין.',
  'Category kind cannot change after finance records reference it.': 'לא ניתן לשנות את סוג הקטגוריה לאחר שרשומות כספיות מפנות אליה.',
  'Choose a valid top-level parent category of the same kind.': 'בחרו קטגוריית אב תקינה מאותו סוג וברמה העליונה.',
  'A category with child categories cannot also have a parent.': 'קטגוריה שיש לה קטגוריות משנה אינה יכולה להיות גם קטגוריית בת.',
  'Tag name is required.': 'יש להזין שם תגית.', 'Choose a valid transaction.': 'בחרו תנועה תקינה.',
  'Choose a valid goal.': 'בחרו יעד תקין.', 'Exchange-rate currencies must be different.': 'מטבעות שער החליפין חייבים להיות שונים.',
  'A rate already exists for this currency pair and date.': 'כבר קיים שער לצמד המטבעות ולתאריך הזה.',
  'Transfers do not have categories.': 'להעברות אין קטגוריות.', 'Choose a valid category.': 'בחרו קטגוריה תקינה.',
  'Choose a valid transaction type.': 'בחרו סוג תנועה תקין.', 'Choose a valid transaction status.': 'בחרו מצב תנועה תקין.',
  'Choose a valid account.': 'בחרו חשבון תקין.', 'Choose a different destination account.': 'בחרו חשבון יעד אחר.',
  'Choose valid tags.': 'בחרו תגיות תקינות.', 'Budget interval must be a positive whole number.': 'מרווח התקציב חייב להיות מספר שלם וחיובי.',
  'Choose a valid budget period.': 'בחרו תקופת תקציב תקינה.', 'Custom budgets require an end date.': 'תקציב מותאם דורש תאריך סיום.',
  'Budget end date must not precede its start date.': 'תאריך סיום התקציב אינו יכול להיות לפני תאריך ההתחלה.',
  'Each category can have only one limit.': 'לכל קטגוריה יכולה להיות מגבלה אחת בלבד.',
  'Category limits must belong to the budget filters.': 'מגבלות קטגוריה חייבות להשתייך למסנני התקציב.',
  'Choose a valid goal kind.': 'בחרו סוג יעד תקין.', 'Starting progress cannot be negative.': 'התקדמות התחלתית אינה יכולה להיות שלילית.',
  'Choose a valid linked account.': 'בחרו חשבון מקושר תקין.', 'Choose a valid recurring transaction kind.': 'בחרו סוג תנועה מחזורית תקין.',
  'Choose a valid recurrence period.': 'בחרו תקופת חזרה תקינה.', 'Schedule end date must not precede its start date.': 'תאריך סיום התזמון אינו יכול להיות לפני תאריך ההתחלה.',
  'Repeat interval must be a positive whole number.': 'מרווח החזרה חייב להיות מספר שלם וחיובי.',
  'Recurring currency must match its account.': 'מטבע התנועה המחזורית חייב להתאים לחשבון.',
  'Couldn’t apply this setting': 'לא ניתן להחיל את ההגדרה', 'Couldn’t finish setup': 'לא ניתן להשלים את ההגדרה',
  'Couldn’t restore': 'לא ניתן לשחזר', 'Couldn’t finish resetting Qashy': 'לא ניתן להשלים את איפוס Qashy',
  'Couldn’t save account': 'לא ניתן לשמור את החשבון', 'Couldn’t archive account': 'לא ניתן להעביר את החשבון לארכיון',
  'Couldn’t save category': 'לא ניתן לשמור את הקטגוריה', 'Couldn’t archive category': 'לא ניתן להעביר את הקטגוריה לארכיון',
  'Couldn’t save transaction': 'לא ניתן לשמור את התנועה', 'Couldn’t delete transaction': 'לא ניתן למחוק את התנועה',
  'Couldn’t delete transactions': 'לא ניתן למחוק את התנועות', 'Couldn’t change category': 'לא ניתן לשנות את הקטגוריה',
  'Couldn’t save budget': 'לא ניתן לשמור את התקציב', 'Couldn’t delete budget': 'לא ניתן למחוק את התקציב',
  'Couldn’t save goal': 'לא ניתן לשמור את היעד', 'Couldn’t delete goal': 'לא ניתן למחוק את היעד',
  'Couldn’t save contribution': 'לא ניתן לשמור את ההפקדה', 'Couldn’t delete contribution': 'לא ניתן למחוק את ההפקדה',
  'Couldn’t save schedule': 'לא ניתן לשמור את התזמון', 'Couldn’t delete schedule': 'לא ניתן למחוק את התזמון',
  'Couldn’t save rate': 'לא ניתן לשמור את השער', 'Couldn’t delete rate': 'לא ניתן למחוק את השער',
  'Couldn’t save appearance': 'לא ניתן לשמור את המראה', 'Couldn’t read CSV': 'לא ניתן לקרוא את קובץ ה־CSV',
  'Couldn’t import CSV': 'לא ניתן לייבא את קובץ ה־CSV', 'Couldn’t export CSV': 'לא ניתן לייצא את קובץ ה־CSV',
  'Couldn’t skip this item': 'לא ניתן לדלג על הפריט', 'Couldn’t mark this item paid': 'לא ניתן לסמן את הפריט כשולם',
  'Delete this transaction?': 'למחוק את התנועה הזו?', 'Delete this schedule?': 'למחוק את התזמון הזה?',
  'Delete this contribution?': 'למחוק את ההפקדה הזו?', 'Delete 1 transaction?': 'למחוק תנועה אחת?',
  'Already generated transactions stay in your ledger.': 'תנועות שכבר נוצרו יישארו ביומן.',
  'They will be removed from your ledger.': 'הן יוסרו מהיומן.', 'Manual contributions are removed with it.': 'ההפקדות הידניות יימחקו יחד איתו.',
  'Past period snapshots are removed with it.': 'תמונות המצב של תקופות קודמות יימחקו יחד איתו.',
  'Transactions that need this rate will report it as missing.': 'תנועות שזקוקות לשער הזה ידווחו שהוא חסר.',
  'The category is hidden from lists and pickers. You can restore it from the Archived section in More.': 'הקטגוריה תוסתר מרשימות ומבוררים. ניתן לשחזר אותה מאזור הארכיון במסך עוד.',
  'The account is hidden from lists and pickers. You can restore it from the Archived section in More.': 'החשבון יוסתר מרשימות ומבוררים. ניתן לשחזר אותו מאזור הארכיון במסך עוד.',
  Archive: 'העברה לארכיון', 'Reset everything': 'איפוס הכול',
  'Reset Qashy?': 'לאפס את Qashy?',
  'This permanently deletes every account, transaction, budget, goal, recurring transaction, exchange rate, category, and setting stored by Qashy on this device. This cannot be undone.': 'פעולה זו מוחקת לצמיתות כל חשבון, תנועה, תקציב, יעד, תנועה מחזורית, שער חליפין, קטגוריה והגדרה ששמורים ב־Qashy במכשיר הזה. לא ניתן לבטל אותה.',
  'Rename the active entry using this name first.': 'שנו תחילה את שם הרשומה הפעילה שמשתמשת בשם הזה.',
  'Restart the app and try again.': 'הפעילו מחדש את האפליקציה ונסו שוב.',
  'Try a compatible category.': 'נסו קטגוריה תואמת.', 'Choose another UTF-8 CSV file.': 'בחרו קובץ CSV אחר בקידוד UTF-8.',
  'No rows were imported.': 'לא יובאו שורות.', 'No transactions found': 'לא נמצאו תנועות',
  'Choose a CSV with a header row and at least one data row.': 'בחרו קובץ CSV עם שורת כותרת ולפחות שורת נתונים אחת.',
  'Import complete': 'הייבוא הושלם',
  'Rejected rows were not imported.': 'שורות שנדחו לא יובאו.', 'Likely duplicates were skipped.': 'כפילויות אפשריות דולגו.',
  Delete: 'מחיקה', Cancel: 'ביטול', 'Primary': 'ראשי', 'A fresh version is ready': 'גרסה חדשה מוכנה', Later: 'אחר כך', Reload: 'טעינה מחדש',
  'Reload when you’re ready. Your finance data stays in IndexedDB.': 'טענו מחדש כשתהיו מוכנים. המידע הפיננסי נשאר ב־IndexedDB.',
  'LOCAL-FIRST FINANCE': 'כספים מקומיים תחילה', 'Only your devices can read your data.': 'רק המכשירים שלכם יכולים לקרוא את הנתונים שלכם.',
  // Seeded category and account names are rendered with `literal`, so they never
  // reach this dictionary — the Hebrew that actually ships lives in
  // `domain/defaults.ts`. Keeping a second copy here meant two unenforced sources
  // of truth for the same eight strings.
  Welcome: 'ברוכים הבאים', 'Page not found': 'הדף לא נמצא', 'Go to Overview': 'מעבר לסקירה',
  'That address doesn’t match anything in Qashy. Your data is untouched.': 'הכתובת הזו אינה תואמת לדבר ב־Qashy. הנתונים שלכם לא נפגעו.',
  'Choose an account before entering an amount.': 'בחרו חשבון לפני הזנת סכום.',
  'Leave blank to calculate through your effective exchange rates.': 'השאירו ריק כדי לחשב לפי שערי החליפין שלכם.',
  'Importing…': 'מייבא…', 'Rent, salary, subscription…': 'שכר דירה, משכורת, מנוי…',
  'Kind is locked because transactions, budgets, goals, or schedules reference this category.': 'סוג הקטגוריה נעול מפני שתנועות, תקציבים, יעדים או תזמונים מפנים אליה.',
  'CSV is transaction portability, not a complete backup. Budgets, goals, schedules, and appearance settings are not included.': 'CSV מיועד להעברת תנועות, לא לגיבוי מלא. תקציבים, יעדים, תזמונים והגדרות מראה אינם נכללים.',
  'This schedule stays paused until its archived account and category are restored.': 'התזמון יישאר מושהה עד לשחזור החשבון והקטגוריה שבארכיון.',
  'Discard changes?': 'לבטל את השינויים?', 'This form has unsaved changes.': 'בטופס יש שינויים שלא נשמרו.',
  Discard: 'ביטול שינויים',
  'Couldn’t preview CSV': 'לא ניתן להציג תצוגה מקדימה של ה־CSV',
  'Check the column mapping and try again.': 'בדקו את מיפוי העמודות ונסו שוב.',
  'Qashy could not reload its local database.': 'Qashy לא הצליח לטעון מחדש את מסד הנתונים המקומי.',
  'Qashy couldn’t refresh': 'Qashy לא הצליח לרענן',
  'What you see may be out of date. Your saved data is untouched.': 'ייתכן שהמוצג אינו מעודכן. הנתונים השמורים שלכם לא נפגעו.',
  Dismiss: 'סגירה',
  'Export Qashy transactions': 'ייצוא תנועות מ־Qashy',
  'Account color': 'צבע החשבון', 'Category kind': 'סוג הקטגוריה',
  'Category icon': 'אייקון הקטגוריה', 'Category color': 'צבע הקטגוריה',
  'Accent color': 'צבע הדגשה', 'Transaction type filter': 'סינון לפי סוג תנועה',
  'Goal type': 'סוג היעד',

  // Sync. Device names, SAS words, pairing codes, relay URLs, and peer-supplied text are
  // data: they render with `literal` and never reach this dictionary. Everything Qashy
  // itself writes does.
  Sync: 'סנכרון', 'Add a device': 'הוספת מכשיר', 'Add device': 'הוספת מכשיר',
  'Review duplicates': 'סקירת כפילויות', 'Recovery phrase': 'משפט שחזור',
  'Reading this device’s sync state…': 'קורא את מצב הסנכרון של המכשיר הזה…',

  // Status vocabulary (sync-summary.ts). Short by design — these land in a settings-row
  // subtitle and in status pills, which are icon + text, never colour alone.
  Off: 'כבוי', 'Not set up': 'לא הוגדר', Locked: 'נעול',
  'Not available on this device': 'לא זמין במכשיר הזה',
  'Up to date': 'מעודכן', 'Syncing…': 'מסנכרן…',
  'No other devices yet': 'אין עדיין מכשירים אחרים',
  'Direct connections only': 'חיבורים ישירים בלבד',
  'Relay unreachable': 'הממסר אינו נגיש', 'Relay rejected this device': 'הממסר דחה את המכשיר הזה',
  'Relay errors': 'שגיאות ממסר', 'Relay problem': 'בעיה בממסר',
  Reachable: 'נגיש', Unreachable: 'אינו נגיש', 'Rejected this device': 'דחה את המכשיר הזה',
  'Having problems': 'יש בעיות', 'Not checked yet': 'עדיין לא נבדק',
  'Never connected': 'מעולם לא התחבר', 'Removed from this vault': 'הוסר מהכספת הזו',
  'Sync is off': 'הסנכרון כבוי', 'Sync isn’t set up yet': 'הסנכרון עדיין לא הוגדר',
  'Sync is locked': 'הסנכרון נעול',
  'This device can’t store a key safely': 'המכשיר הזה אינו יכול לשמור מפתח בבטחה',
  'Some changes couldn’t be applied': 'לא ניתן היה להחיל חלק מהשינויים',
  'You’re offline': 'אתם במצב לא מקוון', 'This device is offline': 'המכשיר הזה אינו מקוון',
  'Can’t reach the relay server': 'לא ניתן להגיע לשרת הממסר',
  'The relay rejected this device': 'הממסר דחה את המכשיר הזה',
  'The relay is having problems': 'יש בעיות בממסר',
  '1 change needs attention': 'שינוי אחד דורש תשומת לב',
  'Sync event': 'אירוע סנכרון', 'Paired a device': 'מכשיר חובר',
  'Removed a device': 'מכשיר הוסר', 'Refused a batch': 'אצווה נדחתה',
  'Everything stays on this device. Turn sync on to keep your own devices in step, end-to-end encrypted.': 'הכול נשאר במכשיר הזה. הפעילו סנכרון כדי לשמור על המכשירים שלכם מסונכרנים, בהצפנה מקצה לקצה.',
  'Enter this device’s passphrase to unlock the vault key. Nothing syncs until you do.': 'הזינו את משפט הסיסמה של המכשיר הזה כדי לשחרר את מפתח הכספת. עד אז שום דבר אינו מסתנכרן.',
  'Qashy could not reach secure storage, so it has nowhere to keep the vault key. Your finance data is untouched.': 'Qashy לא הצליח להגיע לאחסון המאובטח, ולכן אין לו מקום לשמור את מפתח הכספת. הנתונים הפיננסיים שלכם לא נפגעו.',
  'They are kept, passed on to your other devices, and retried on every sync — so a correction from any device fixes them on its own.': 'הם נשמרים, מועברים למכשירים האחרים שלכם ומנוסים שוב בכל סנכרון — כך שתיקון מכל מכשיר פותר אותם מעצמו.',
  'No relay is set, so your devices sync when both are open at the same time and on a network that lets them reach each other.': 'לא הוגדר ממסר, ולכן המכשירים שלכם מסתנכרנים כששניהם פתוחים בו־זמנית וברשת שמאפשרת להם להגיע זה לזה.',
  'Pair a second device to start. You compare a six-word code on both screens, and nothing is sent until you confirm it matches.': 'חברו מכשיר שני כדי להתחיל. תשוו קוד של שש מילים בשני המסכים, ושום דבר אינו נשלח עד שתאשרו שהוא זהה.',
  'This is the only device in the vault. Add another and Qashy keeps them in step.': 'זהו המכשיר היחיד בכספת. הוסיפו עוד אחד ו־Qashy ישמור עליהם מסונכרנים.',
  'Paired and ready. Nothing has needed to move between your devices yet.': 'מחובר ומוכן. עדיין לא היה צורך להעביר דבר בין המכשירים שלכם.',
  'Devices on the same network still sync directly. Only catching up while your other device is closed needs the relay.': 'מכשירים באותה רשת ממשיכים להסתנכרן ישירות. רק השלמת פערים כשהמכשיר האחר סגור זקוקה לממסר.',
  'It answered but refused this vault. Check the relay address in Sync settings — a relay that was replaced or redeployed is the usual cause.': 'הוא ענה אך דחה את הכספת הזו. בדקו את כתובת הממסר בהגדרות הסנכרון — ממסר שהוחלף או נפרס מחדש הוא הסיבה הרגילה.',
  'It answers, but uploads are failing. Devices on the same network still sync directly.': 'הוא עונה, אך ההעלאות נכשלות. מכשירים באותה רשת ממשיכים להסתנכרן ישירות.',
  'Nothing is wrong with sync. Your changes are saved here and will catch up when this device is back on a network.': 'אין תקלה בסנכרון. השינויים שלכם שמורים כאן וישלימו פערים כשהמכשיר הזה יחזור לרשת.',

  // Relative times. `relative-time.ts` deliberately emits a small closed set of English
  // shapes instead of `Intl.RelativeTimeFormat`, so that every one of them has an entry
  // here or a `translateDynamic` pattern below.
  'just now': 'לפני רגע', 'over a year ago': 'לפני יותר משנה',

  // /sync
  'Sync now': 'סנכרון עכשיו', Pause: 'השהיה', 'Resume sync': 'המשך סנכרון',
  'Set up sync': 'הגדרת סנכרון', 'How this works': 'איך זה עובד',
  Activity: 'פעילות', Recovery: 'שחזור', 'Danger zone': 'אזור מסוכן',
  'Directly when it can': 'ישירות כשאפשר',
  'A blind drop-box when it can’t': 'תיבת הפקדה עיוורת כשלא',
  'No account, ever': 'ללא חשבון, אף פעם',
  'Only your devices can read it': 'רק המכשירים שלכם יכולים לקרוא אותו',
  // The bodies under "How this works" are the app's privacy claim stated in prose. Leaving
  // them English would show a Hebrew reader the claim in a language they did not choose,
  // which is exactly the wrong place to fall back.
  'Every change is sealed on the device that made it, with a key that exists only on devices you paired in person. Nothing else can open it.': 'כל שינוי נאטם במכשיר שיצר אותו, במפתח שקיים רק במכשירים שחיברתם פנים אל פנים. שום דבר אחר אינו יכול לפתוח אותו.',
  'On the same network your devices talk to each other and contact no server at all.': 'באותה רשת המכשירים שלכם מדברים זה עם זה ואינם פונים לשום שרת.',
  'When your other device is closed, sealed changes wait on a relay. It sees a random-looking address and padded ciphertext — never who you are, what changed, or how much you have.': 'כשהמכשיר האחר שלכם סגור, שינויים אטומים ממתינים בממסר. הוא רואה כתובת שנראית אקראית וטקסט מוצפן מרופד — לעולם לא מי אתם, מה השתנה או כמה יש לכם.',
  'There is no sign-in, no server-side identity, and nothing to recover through us. The recovery phrase is the only key.': 'אין התחברות, אין זהות בצד השרת ואין דבר לשחזר דרכנו. משפט השחזור הוא המפתח היחיד.',
  'The last sync didn’t finish': 'הסנכרון האחרון לא הושלם',
  'Your data is untouched, and the next sync retries on its own.': 'הנתונים שלכם לא נפגעו, והסנכרון הבא ינסה שוב מעצמו.',
  'Some changes on this device are still being signed. They go out on the next sync.': 'חלק מהשינויים במכשיר הזה עדיין נחתמים. הם יישלחו בסנכרון הבא.',
  'Sends, receives, and anything refused will appear here.': 'שליחות, קליטות וכל דבר שנדחה יופיעו כאן.',
  'The log records how much moved and in which direction — never what changed. It is safe to share when asking for help.': 'היומן מתעד כמה עבר ובאיזה כיוון — לעולם לא מה השתנה. אפשר לשתף אותו בבטחה כשמבקשים עזרה.',
  'Twenty-four words that are the vault. Anyone holding them holds your data.': 'עשרים וארבע מילים שהן הכספת עצמה. מי שמחזיק בהן מחזיק בנתונים שלכם.',
  'Replace the vault key': 'החלפת מפתח הכספת', 'Replace the vault key?': 'להחליף את מפתח הכספת?',
  'Replace key': 'החלפת המפתח', 'Replacing…': 'מחליף…',
  'For a lost device. Every device must be paired again.': 'למכשיר שאבד. כל מכשיר יצטרך להתחבר מחדש.',
  'Every device is removed and must be paired again, including this one’s partners. Do this when a device is lost: it makes the copy of the drop-box that device knows about unreadable to it.': 'כל המכשירים מוסרים ויצטרכו להתחבר מחדש, כולל אלה שמחוברים למכשיר הזה. עשו זאת כשמכשיר אובד: הפעולה הופכת את עותק תיבת ההפקדה שאותו מכשיר מכיר לבלתי קריא עבורו.',
  'Leave this vault': 'יציאה מהכספת', 'Leave this vault?': 'לצאת מהכספת הזו?',
  'Leave vault': 'יציאה מהכספת', 'Leaving…': 'יוצא…',
  'Stop syncing and forget the key. Your finance data stays on this device.': 'להפסיק לסנכרן ולשכוח את המפתח. הנתונים הפיננסיים נשארים במכשיר הזה.',
  'This device stops syncing and forgets the vault key. Your accounts, transactions, budgets, and goals stay exactly as they are on this device. Your other devices keep syncing with each other.': 'המכשיר הזה יפסיק לסנכרן וישכח את מפתח הכספת. החשבונות, התנועות, התקציבים והיעדים שלכם יישארו בדיוק כפי שהם במכשיר הזה. המכשירים האחרים שלכם ימשיכו להסתנכרן ביניהם.',
  'Couldn’t pause sync': 'לא ניתן להשהות את הסנכרון',
  'Couldn’t resume sync': 'לא ניתן להמשיך את הסנכרון',
  'Couldn’t replace the vault key': 'לא ניתן להחליף את מפתח הכספת',
  'Couldn’t leave the vault': 'לא ניתן לצאת מהכספת',
  'Nothing was changed.': 'שום דבר לא שונה.',

  // /sync → Connections
  Connections: 'חיבורים', 'Direct connections': 'חיבורים ישירים', 'Relay server': 'שרת ממסר',
  'Devices talk to each other, encrypted end to end. On the same network this contacts no server at all.': 'המכשירים מדברים זה עם זה בהצפנה מקצה לקצה. באותה רשת אין פנייה לשום שרת.',
  'Holds sealed changes for a device that is closed. It can never read them.': 'שומר שינויים חתומים עבור מכשיר שסגור. הוא לעולם אינו יכול לקרוא אותם.',
  'Check now': 'בדיקה עכשיו', 'Checking…': 'בודק…',
  'Change addresses': 'שינוי הכתובות', 'Hide addresses': 'הסתרת הכתובות',
  'Relay address': 'כתובת הממסר', 'Save addresses': 'שמירת הכתובות',
  'Leave this blank to contact nothing but devices on your own network.': 'השאירו ריק כדי לפנות רק למכשירים ברשת שלכם.',
  'STUN servers': 'שרתי STUN',
  'Used only when a direct connection fails. A STUN server learns an IP address and never sees your data.': 'בשימוש רק כשחיבור ישיר נכשל. שרת STUN לומד כתובת IP ולעולם אינו רואה את הנתונים שלכם.',
  'TURN server': 'שרת TURN', 'TURN username': 'שם משתמש ל־TURN', 'TURN password': 'סיסמה ל־TURN',
  'Only add one you run yourself. A TURN server sees both devices’ addresses and how much data moves between them.': 'הוסיפו רק שרת שאתם עצמכם מפעילים. שרת TURN רואה את הכתובות של שני המכשירים וכמה נתונים עוברים ביניהם.',
  'What the server said': 'מה השרת אמר',
  'No relay address is set, so this device only syncs when another one is open at the same time.': 'לא הוגדרה כתובת ממסר, ולכן המכשיר הזה מסתנכרן רק כשמכשיר אחר פתוח בו־זמנית.',
  'Couldn’t save these addresses': 'לא ניתן לשמור את הכתובות',
  'Couldn’t save that': 'לא ניתן לשמור את זה',
  'Couldn’t reach the relay': 'לא ניתן להגיע לממסר',
  'Check the address and try again.': 'בדקו את הכתובת ונסו שוב.',
  'Check them and try again.': 'בדקו אותן ונסו שוב.',
  'That address is not valid.': 'הכתובת הזו אינה תקינה.',
  'Try again in a moment.': 'נסו שוב בעוד רגע.',

  // /sync → Devices
  Devices: 'מכשירים', 'This device': 'המכשיר הזה', 'Unnamed device': 'מכשיר ללא שם',
  'Rename this device': 'שינוי שם המכשיר', 'Device name': 'שם המכשיר',
  Save: 'שמירה', Remove: 'הסרה', 'Remove this device?': 'להסיר את המכשיר הזה?',
  'Only your paired devices ever see this. It is sent encrypted, and the relay never learns it.': 'רק המכשירים המחוברים שלכם רואים אותו. הוא נשלח מוצפן, והממסר לעולם אינו לומד אותו.',
  'It stops sending and receiving changes here. It keeps the copy of your data it already has — to make that copy useless, rotate the vault key afterwards.': 'הוא יפסיק לשלוח ולקבל שינויים כאן. העותק של הנתונים שכבר יש לו יישאר אצלו — כדי להפוך אותו לחסר תועלת, החליפו לאחר מכן את מפתח הכספת.',
  'Pair a second device and Qashy keeps them in step. You compare a six-word code on both screens first, so nothing is sent to a device you didn’t confirm.': 'חברו מכשיר שני ו־Qashy ישמור עליהם מסונכרנים. תחילה תשוו קוד של שש מילים בשני המסכים, כך שדבר אינו נשלח למכשיר שלא אישרתם.',
  'Removed devices stay listed so your history keeps its author. They can no longer send or receive changes.': 'מכשירים שהוסרו נשארים ברשימה כדי שההיסטוריה שלכם תשמור על מחברה. הם אינם יכולים עוד לשלוח או לקבל שינויים.',
  'Couldn’t remove that device': 'לא ניתן להסיר את המכשיר',
  'Couldn’t rename this device': 'לא ניתן לשנות את שם המכשיר',
  'Try a different name.': 'נסו שם אחר.',

  // /sync-pair
  'This device has my data': 'במכשיר הזה נמצאים הנתונים שלי',
  'Shows a code for the other device to scan.': 'מציג קוד שהמכשיר האחר יסרוק.',
  'Add this device to a vault': 'הוספת המכשיר הזה לכספת',
  'Scans a code shown by a device that is already set up.': 'סורק קוד שמוצג במכשיר שכבר מוגדר.',
  'Both devices end up holding the same key, and only those two can read anything. Start on whichever one has the data you want to keep.': 'שני המכשירים יחזיקו בסופו של דבר באותו מפתח, ורק הם יכולים לקרוא משהו. התחילו במכשיר שבו נמצאים הנתונים שברצונכם לשמור.',
  'Needs a relay address first — the two devices have nowhere to meet without one.': 'נדרשת קודם כתובת ממסר — בלעדיה אין לשני המכשירים מקום להיפגש.',
  'Not available — this device is already part of a vault. Removing it from the other device is the way out.': 'לא זמין — המכשיר הזה כבר חלק מכספת. הדרך לצאת היא להסיר אותו מהמכשיר האחר.',
  'Set a relay address first': 'הגדירו קודם כתובת ממסר',
  'Showing a code needs somewhere the two devices can agree to meet. The relay never sees your data — it forwards sealed bytes between devices that already hold each other’s keys. Add its address under Connections in Sync settings.': 'הצגת קוד דורשת מקום שבו שני המכשירים יכולים להסכים להיפגש. הממסר לעולם אינו רואה את הנתונים שלכם — הוא מעביר בתים חתומים בין מכשירים שכבר מחזיקים במפתחות זה של זה. הוסיפו את כתובתו תחת ״חיבורים״ בהגדרות הסנכרון.',
  'Open sync settings': 'פתיחת הגדרות הסנכרון',
  'Scan this on the other device': 'סרקו את זה במכשיר האחר',
  'Open Qashy there, go to More → Sync → Add device, and choose “Add this device to a vault”.': 'פתחו שם את Qashy, עברו לעוד ← סנכרון ← הוספת מכשיר ובחרו ״הוספת המכשיר הזה לכספת״.',
  'The code works once and expires after a minute and a half.': 'הקוד עובד פעם אחת ופג לאחר דקה וחצי.',
  'Preparing a code…': 'מכין קוד…', 'Preparing…': 'מכין…', 'Pairing…': 'מחבר…',
  'This code has expired. Codes are single use and short-lived on purpose.': 'הקוד הזה פג. הקודים הם לשימוש חד־פעמי וקצרי מועד בכוונה.',
  'Show a new code': 'הצגת קוד חדש', 'Can’t scan?': 'לא מצליחים לסרוק?',
  'Hide the typed code': 'הסתרת הקוד להקלדה',
  'Type or paste this into the other device instead of scanning. Treat it like the code itself — it works once, and only for the next minute or so.': 'הקלידו או הדביקו את זה במכשיר האחר במקום לסרוק. התייחסו לזה כמו לקוד עצמו — הוא עובד פעם אחת, ורק בדקה הקרובה בערך.',
  'Pairing code for the other device to scan': 'קוד חיבור שהמכשיר האחר יסרוק',
  'Scan the other device': 'סרקו את המכשיר האחר',
  'Open Sync → Add device on the device that already has your data, and point this one at the code it shows.': 'פתחו סנכרון ← הוספת מכשיר במכשיר שבו כבר נמצאים הנתונים שלכם, וכוונו את המכשיר הזה לקוד שמוצג בו.',
  'Waiting for the other device. The next screen shows six words that must be identical on both — that comparison is what makes a photographed code useless.': 'ממתין למכשיר האחר. המסך הבא מציג שש מילים שחייבות להיות זהות בשניהם — ההשוואה הזו היא מה שהופך קוד מצולם לחסר תועלת.',
  'Do these words match?': 'האם המילים האלה זהות?',
  'The other device is showing six words too. Compare them now, in the same order. If even one differs, stop — someone else may be trying to join.': 'גם המכשיר האחר מציג שש מילים. השוו אותן עכשיו, באותו סדר. אם אפילו אחת שונה, עצרו — ייתכן שמישהו אחר מנסה להתחבר.',
  'They match': 'הן זהות', 'They don’t match': 'הן אינן זהות',
  'Nothing has been sent yet. Your vault key only leaves this device after you confirm.': 'שום דבר לא נשלח עדיין. מפתח הכספת עוזב את המכשיר הזה רק לאחר שתאשרו.',
  'Pairing stopped': 'החיבור הופסק', 'Start over': 'התחלה מחדש',
  'Pairing was stopped and nothing was sent. Different words on the two screens can mean someone else tried to join — start again, and keep the code on screen only while the other device is scanning it.': 'החיבור הופסק ושום דבר לא נשלח. מילים שונות בשני המסכים יכולות להעיד שמישהו אחר ניסה להתחבר — התחילו מחדש, והשאירו את הקוד על המסך רק בזמן שהמכשיר האחר סורק אותו.',
  'Device added': 'המכשיר נוסף', Paired: 'מחובר', 'Name this device': 'תנו שם למכשיר הזה',
  'Both devices now hold the same vault key.': 'שני המכשירים מחזיקים כעת באותו מפתח כספת.',
  'Both devices now hold the same vault key. Changes flow in both directions from here.': 'שני המכשירים מחזיקים כעת באותו מפתח כספת. מכאן השינויים זורמים בשני הכיוונים.',
  'This device joined the vault': 'המכשיר הזה הצטרף לכספת',
  'Your data from both devices is being combined. Anything you created on both will show up twice until you review it.': 'הנתונים משני המכשירים משולבים כעת. כל דבר שיצרתם בשניהם יופיע פעמיים עד שתסקרו אותו.',
  'If both devices already had data': 'אם בשני המכשירים כבר היו נתונים',
  'Anything you created on both is now in the vault twice. Qashy renamed the collisions rather than guessing which are the same — the review screen is where you decide.': 'כל דבר שיצרתם בשניהם נמצא כעת בכספת פעמיים. Qashy שינה את שמות ההתנגשויות במקום לנחש מה זהה — מסך הסקירה הוא המקום שבו אתם מחליטים.',
  'Sync could not be set up on this device.': 'לא ניתן היה להגדיר סנכרון במכשיר הזה.',
  'This device’s vault key could not be read.': 'לא ניתן היה לקרוא את מפתח הכספת של המכשיר הזה.',
  'The other device did not complete pairing.': 'המכשיר האחר לא השלים את החיבור.',
  'That code could not be used. Show a fresh one and try again.': 'לא ניתן היה להשתמש בקוד הזה. הציגו קוד חדש ונסו שוב.',
  'Pairing could not be completed.': 'לא ניתן היה להשלים את החיבור.',
  'Unlock this device first': 'שחררו קודם את המכשיר הזה',
  'The vault key on this device is behind a passphrase. Unlock it from the sync screen, then come back.': 'מפתח הכספת במכשיר הזה מוגן במשפט סיסמה. שחררו אותו ממסך הסנכרון ואז חזרו לכאן.',
  'Qashy could not reach secure storage, so it has nowhere to keep the vault key. Pairing is disabled here. Your finance data is untouched.': 'Qashy לא הצליח להגיע לאחסון המאובטח, ולכן אין לו מקום לשמור את מפתח הכספת. החיבור מושבת כאן. הנתונים הפיננסיים שלכם לא נפגעו.',

  // QR code and scanner
  'This code is too long to show as a QR code. Use the manual code instead.': 'הקוד הזה ארוך מדי להצגה כקוד QR. השתמשו בקוד הידני במקום.',
  'Qashy needs the camera to scan the code': 'Qashy זקוק למצלמה כדי לסרוק את הקוד',
  'The camera is used only to read the pairing code on your other device. No photo is taken and nothing is uploaded.': 'המצלמה משמשת רק לקריאת קוד החיבור במכשיר האחר שלכם. לא מצולמת תמונה ושום דבר אינו מועלה.',
  'Allow camera': 'אישור מצלמה', 'Open settings': 'פתיחת ההגדרות',
  'This device can’t use a camera here, so enter the code shown on your other device.': 'המכשיר הזה אינו יכול להשתמש במצלמה כאן, לכן הזינו את הקוד שמוצג במכשיר האחר שלכם.',
  'Pairing code': 'קוד חיבור',
  'Paste the code from your other device': 'הדביקו את הקוד מהמכשיר האחר שלכם',
  'Can’t scan? Enter the code': 'לא מצליחים לסרוק? הזינו את הקוד',
  'Scan a code instead': 'סריקת קוד במקום',

  // /sync-merge
  'When two devices that both already had data are paired, anything you created on both arrives twice. Qashy renamed the collisions rather than guessing — pick the ones that really are the same thing.': 'כששני מכשירים שבשניהם כבר היו נתונים מתחברים, כל דבר שיצרתם בשניהם מגיע פעמיים. Qashy שינה את שמות ההתנגשויות במקום לנחש — בחרו את אלה שהם באמת אותו דבר.',
  'Nothing looks duplicated': 'שום דבר אינו נראה כפול',
  'Qashy found no records that appear twice. If you have just paired a device, sync once and check again.': 'Qashy לא מצא רשומות שמופיעות פעמיים. אם רק חיברתם מכשיר, סנכרנו פעם אחת ובדקו שוב.',
  'Back to sync': 'חזרה לסנכרון', 'Select all': 'בחירת הכול',
  'Copies removed': 'עותקים שהוסרו', 'Records updated': 'רשומות שעודכנו',
  'Kept separate': 'נשמרו בנפרד', Merge: 'מיזוג', 'Merging…': 'ממזג…',
  'Merge these records?': 'למזג את הרשומות האלה?',
  'The copies are deleted and everything that referred to them is pointed at the record you kept. Your totals do not change, but this cannot be undone from here.': 'העותקים נמחקים וכל מה שהפנה אליהם מכוון לרשומה שהשארתם. הסכומים שלכם אינם משתנים, אך לא ניתן לבטל זאת מכאן.',
  'These merges conflict.': 'המיזוגים האלה מתנגשים.',
  'Keep this one, remove 1 copy': 'להשאיר את זו ולהסיר עותק אחד',
  'Merging accounts and categories can reveal duplicate transactions that could not be matched before. Check the list again below.': 'מיזוג חשבונות וקטגוריות עשוי לחשוף תנועות כפולות שלא ניתן היה להתאים קודם. בדקו את הרשימה שוב למטה.',
  'Skipping this is fine. Renamed duplicates are a valid resting state, and this screen stays available from Sync whenever you want to come back to it.': 'אין בעיה לדלג על זה. כפילויות ששמן שונה הן מצב תקין, והמסך הזה נשאר זמין מהסנכרון בכל פעם שתרצו לחזור אליו.',
  'Couldn’t merge those records': 'לא ניתן למזג את הרשומות האלה',
  Untitled: 'ללא כותרת',

  // /sync-recovery
  'Your recovery phrase': 'משפט השחזור שלכם',
  'Twenty-four words that encode this vault’s key. There is no account behind Qashy and no way for anyone to reset this for you — these words are the only copy of the key that exists outside your devices.': 'עשרים וארבע מילים שמקודדות את מפתח הכספת הזו. אין חשבון מאחורי Qashy ואין דרך שמישהו יאפס אותן עבורכם — המילים האלה הן העותק היחיד של המפתח שקיים מחוץ למכשירים שלכם.',
  'Show phrase': 'הצגת המשפט', 'Hide phrase': 'הסתרת המשפט', 'Reading…': 'קורא…',
  'Show the recovery phrase?': 'להציג את משפט השחזור?',
  'These words are your entire vault. Anyone who reads them can open every account, transaction, and balance you have. Check that nobody can see your screen and that you are not sharing or recording it.': 'המילים האלה הן הכספת כולה. כל מי שקורא אותן יכול לפתוח כל חשבון, תנועה ויתרה שיש לכם. ודאו שאיש אינו רואה את המסך שלכם ושאינכם משתפים או מקליטים אותו.',
  'Anyone holding these words holds your data': 'מי שמחזיק במילים האלה מחזיק בנתונים שלכם',
  'Losing them is not the same as losing a password': 'אובדן שלהן אינו כמו אובדן סיסמה',
  'There is no copy button, on purpose': 'אין כפתור העתקה, בכוונה',
  'Treat them exactly like the money itself. A password manager or a piece of paper somewhere only you can reach are both fine. A photo in your camera roll or a note that syncs to a cloud account are not.': 'התייחסו אליהן בדיוק כמו אל הכסף עצמו. מנהל סיסמאות או פתק במקום שרק אתם מגיעים אליו — שניהם בסדר. צילום בגלריה או פתק שמסתנכרן לחשבון ענן — לא.',
  'The clipboard is readable by other apps and, on some systems, by your other computers. Write the words down or type them straight into a password manager instead.': 'הלוח ניתן לקריאה על ידי אפליקציות אחרות, ובמערכות מסוימות גם על ידי המחשבים האחרים שלכם. במקום זאת רשמו את המילים או הקלידו אותן ישירות לתוך מנהל סיסמאות.',
  'Qashy cannot reset, re-issue, or recover this. If you lose every paired device and these words, the data on them is gone.': 'Qashy אינו יכול לאפס, להנפיק מחדש או לשחזר את זה. אם תאבדו את כל המכשירים המחוברים ואת המילים האלה, הנתונים שבהם אבדו.',
  'Check what you wrote down': 'בדיקת מה שרשמתם',
  'Type the words back in order. A phrase with one word wrong looks completely normal and restores nothing, and this is the only moment you can find that out cheaply.': 'הקלידו את המילים בחזרה לפי הסדר. משפט שבו מילה אחת שגויה נראה נורמלי לחלוטין ואינו משחזר דבר, וזה הרגע היחיד שבו תוכלו לגלות זאת בזול.',
  'That matches': 'זה תואם', 'That does not match yet': 'זה עדיין אינו תואם',
  'What this phrase can do': 'מה המשפט הזה יכול לעשות',
  'The phrase is the key, not the data. It opens a vault backup file; on its own it restores nothing, because your records only ever live on your devices and in a backup you saved. Sealed changes waiting on the relay are addressed to specific devices, so a replacement device cannot read them either.': 'המשפט הוא המפתח, לא הנתונים. הוא פותח קובץ גיבוי של הכספת; בפני עצמו הוא אינו משחזר דבר, משום שהרשומות שלכם נמצאות רק במכשירים שלכם ובגיבוי ששמרתם. שינויים חתומים שממתינים בממסר ממוענים למכשירים מסוימים, ולכן גם מכשיר חלופי אינו יכול לקרוא אותם.',
  'So a complete plan is these words plus a backup file, kept apart from each other. Without a backup, a replacement device is added by pairing it with a device you still have — which is why a second paired device is worth keeping.': 'לכן תוכנית שלמה היא המילים האלה יחד עם קובץ גיבוי, כשהם נשמרים בנפרד זה מזה. ללא גיבוי, מכשיר חלופי מתווסף בחיבורו למכשיר שעדיין נמצא ברשותכם — ולכן שווה להחזיק מכשיר מחובר שני.',
  'No vault on this device': 'אין כספת במכשיר הזה',
  'There is no vault on this device': 'אין כספת במכשיר הזה',
  'A recovery phrase exists once this device is part of a vault. Set up sync first.': 'משפט שחזור קיים רק כאשר המכשיר הזה חלק מכספת. הגדירו קודם סנכרון.',
  'Set up sync first, then come back.': 'הגדירו קודם סנכרון ואז חזרו לכאן.',
  'This device’s key is locked': 'המפתח של המכשיר הזה נעול',
  'Unlock it from the sync screen, then come back.': 'שחררו אותו ממסך הסנכרון ואז חזרו לכאן.',
  'Couldn’t read the vault key': 'לא ניתן לקרוא את מפתח הכספת',
  'Unlock this device and try again.': 'שחררו את המכשיר הזה ונסו שוב.',

  // /sync-transfer. File names and extensions are Qashy's own and stay Latin — `.qashyvault`
  // is what the file picker shows, so translating it would send someone looking for a file
  // that does not exist. Counts render as their own `literal` node beside a fixed label, so
  // none of the tallies below need a `translateDynamic` pattern.
  'Backup & transfer': 'גיבוי והעברה',
  'Save an encrypted copy of this device, or move changes by file.': 'שמרו עותק מוצפן של המכשיר הזה, או העבירו שינויים באמצעות קובץ.',
  'Restore from a backup': 'שחזור מגיבוי',
  'Put an encrypted vault backup onto this device.': 'העלו גיבוי כספת מוצפן למכשיר הזה.',
  'A vault backup is a complete, encrypted copy of this device — its key, its records, and its history — in one file you keep. It is the only thing that can put your data on a replacement device when every device you had is gone.': 'גיבוי כספת הוא עותק מוצפן ומלא של המכשיר הזה — המפתח שלו, הרשומות שלו וההיסטוריה שלו — בקובץ אחד שנשאר אצלכם. זה הדבר היחיד שיכול להחזיר את הנתונים שלכם למכשיר חלופי כשכל המכשירים שהיו לכם אבדו.',

  // Vault backup (export)
  'Create a vault backup': 'יצירת גיבוי כספת',
  'Choose what opens the file later. A passphrase is right for a copy you store somewhere else; the recovery phrase is right if those twenty-four words are already written down and this file will sit beside them.': 'בחרו מה יפתח את הקובץ בהמשך. משפט סיסמה מתאים לעותק שתשמרו במקום אחר; משפט השחזור מתאים אם עשרים וארבע המילים כבר רשומות והקובץ הזה יישמר לצידן.',
  'How the backup is protected': 'כיצד הגיבוי מוגן',
  'A passphrase': 'משפט סיסמה', 'My recovery phrase': 'משפט השחזור שלי',
  Passphrase: 'משפט סיסמה', 'Passphrase again': 'משפט הסיסמה שוב',
  'At least 8 characters. Qashy cannot reset this — the file is unreadable without it.': 'לפחות 8 תווים. Qashy אינו יכול לאפס אותו — הקובץ אינו קריא בלעדיו.',
  'These two do not match.': 'השניים אינם תואמים.',
  'Nothing to type. The file is sealed with the key this device already holds, so the phrase that opens it is this vault’s own — which also means a file written this way cannot be opened by a phrase you mistyped into a box.': 'אין מה להקליד. הקובץ נחתם עם המפתח שכבר נמצא במכשיר הזה, ולכן המשפט שפותח אותו הוא זה של הכספת עצמה — מה שגם אומר שקובץ שנכתב כך לא ייפתח עם משפט שהוקלד בשגיאה.',
  'Create backup': 'יצירת גיבוי', 'Working…': 'עובד…', 'Backup saved': 'הגיבוי נשמר',
  'Treat the file exactly like the recovery phrase: whoever can open it can read every account, transaction, and balance you have. Storing it somewhere only you can reach is the whole job.': 'התייחסו לקובץ בדיוק כמו למשפט השחזור: כל מי שיכול לפתוח אותו יכול לקרוא כל חשבון, תנועה ויתרה שיש לכם. לשמור אותו במקום שרק אתם מגיעים אליו — זו כל המשימה.',
  'Save Qashy vault backup': 'שמירת גיבוי כספת של Qashy',
  'Couldn’t create the backup': 'לא ניתן ליצור את הגיבוי',

  // Sync files (.qashysync)
  'Sync with a file': 'סנכרון באמצעות קובץ',
  'Carry your changes to another of your devices yourself — AirDrop, a USB stick, an email to yourself. No relay, no signaling, no network of any kind is involved. This is the path when the relay is down, or when two devices are never online together.': 'העבירו את השינויים שלכם למכשיר אחר שלכם בעצמכם — AirDrop, החסן נייד, או מייל לעצמכם. אין ממסר, אין איתות, ואין רשת מכל סוג שהוא. זו הדרך כשהממסר מושבת, או כששני מכשירים לעולם אינם מקוונים יחד.',
  'Export changes': 'ייצוא שינויים', 'Sealing…': 'חותם…',
  'Import a sync file': 'ייבוא קובץ סנכרון', 'Applying…': 'מחיל…',
  'Sealed batches': 'אצוות חתומות', 'Devices covered': 'מכשירים מכוסים',
  'Every device is already up to date': 'כל המכשירים כבר מעודכנים',
  'Exporting again later is harmless. Changes stay queued until a device confirms it received them, so a file that never arrives costs nothing but a second export.': 'ייצוא נוסף בהמשך אינו מזיק. שינויים נשארים בתור עד שמכשיר מאשר שקיבל אותם, ולכן קובץ שלא מגיע לעולם עולה רק ייצוא נוסף.',
  'Changes applied': 'שינויים שהוחלו', 'For another device': 'עבור מכשיר אחר', Refused: 'נדחו',
  'Batches meant for a different device in this vault are skipped, not lost — one file carries a share for each of them. Anything refused is recorded on the sync screen with the reason.': 'אצוות שמיועדות למכשיר אחר בכספת הזו מדולגות, לא אובדות — קובץ אחד נושא מנה עבור כל אחד מהם. כל דחייה נרשמת במסך הסנכרון יחד עם הסיבה.',
  'Send Qashy changes': 'שליחת שינויים מ־Qashy',
  'Nothing to send': 'אין מה לשלוח', 'Nothing was applied': 'שום דבר לא הוחל',
  'Couldn’t create the sync file': 'לא ניתן ליצור את קובץ הסנכרון',
  'Couldn’t import that sync file': 'לא ניתן לייבא את קובץ הסנכרון הזה',
  'Sync is paused on this device. Resume it from the sync screen, then try again.': 'הסנכרון מושהה במכשיר הזה. חדשו אותו ממסך הסנכרון ואז נסו שוב.',
  'This device is not part of a vault, so there is nothing to send or receive.': 'המכשיר הזה אינו חלק מכספת, ולכן אין מה לשלוח או לקבל.',
  'This device’s key is locked. Unlock it from the sync screen and try again.': 'המפתח של המכשיר הזה נעול. שחררו אותו ממסך הסנכרון ונסו שוב.',
  'This device can’t read its stored key, so nothing can be sealed or opened.': 'המכשיר הזה אינו יכול לקרוא את המפתח השמור שלו, ולכן שום דבר אינו ניתן לחתימה או לפתיחה.',

  // Restore
  'Everything currently on this device is replaced by what the file holds. The restored device carries on as the one that made the backup, so restore onto a replacement — never alongside a device that is still in use.': 'כל מה שנמצא כעת במכשיר הזה יוחלף במה שהקובץ מכיל. המכשיר המשוחזר ממשיך בתור זה שיצר את הגיבוי, ולכן שחזרו למכשיר חלופי — לעולם לא לצד מכשיר שעדיין בשימוש.',
  'Choose a backup file': 'בחירת קובץ גיבוי', 'Choose a different file': 'בחירת קובץ אחר',
  'The passphrase you chose when this backup was created.': 'משפט הסיסמה שבחרתם כשהגיבוי הזה נוצר.',
  'Open backup': 'פתיחת הגיבוי', 'Opening…': 'פותח…', 'Backup opened': 'הגיבוי נפתח',
  'Made on': 'נוצר בתאריך', 'Made by': 'נוצר על ידי',
  Records: 'רשומות', 'Other devices': 'מכשירים אחרים',
  'Replace this device with this backup': 'החלפת המכשיר הזה בגיבוי הזה',
  'This cannot be undone from inside Qashy.': 'לא ניתן לבטל זאת מתוך Qashy.',
  'Restore this backup?': 'לשחזר את הגיבוי הזה?',
  'Everything currently on this device — accounts, transactions, budgets, goals, and schedules — is replaced by what is in this file. This device then continues as the device that made the backup, so do not do this while that device is still in use.': 'כל מה שנמצא כעת במכשיר הזה — חשבונות, תנועות, תקציבים, יעדים ותזמונים — יוחלף במה שנמצא בקובץ הזה. המכשיר הזה ימשיך אז בתור המכשיר שיצר את הגיבוי, ולכן אל תעשו זאת בזמן שאותו מכשיר עדיין בשימוש.',
  'Backup restored': 'הגיבוי שוחזר',
  'Your data is back on this device. Your other devices already know it, so sync continues from where the backup left off.': 'הנתונים שלכם חזרו למכשיר הזה. המכשירים האחרים שלכם כבר מכירים אותו, ולכן הסנכרון ממשיך מהנקודה שבה הגיבוי הפסיק.',
  'That isn’t a Qashy backup': 'זה אינו גיבוי של Qashy',
  'Choose the .qashyvault file you saved from Sync → Backup & transfer.': 'בחרו את קובץ ה־‎.qashyvault ששמרתם מסנכרון ← גיבוי והעברה.',
  'Couldn’t read that file': 'לא ניתן לקרוא את הקובץ הזה',
  'Couldn’t open that backup': 'לא ניתן לפתוח את הגיבוי הזה',
  'Couldn’t restore that backup': 'לא ניתן לשחזר את הגיבוי הזה',
  'No backup file? A device that still has your data can add this one from Sync → Add a device instead, which copies the vault across without a file at all.': 'אין קובץ גיבוי? מכשיר שהנתונים שלכם עדיין נמצאים בו יכול להוסיף את המכשיר הזה דרך סנכרון ← הוספת מכשיר, מה שמעתיק את הכספת ללא קובץ כלל.',
  'Restoring onto this device': 'שחזור למכשיר הזה',
  'Not offered here, because this device already holds a vault and restoring would replace it. A device that needs restoring is one with nothing on it — or one that has left this vault from Sync → Danger zone first.': 'לא מוצע כאן, משום שהמכשיר הזה כבר מחזיק כספת ושחזור יחליף אותה. מכשיר שזקוק לשחזור הוא מכשיר שאין בו דבר — או כזה שיצא מהכספת הזו קודם דרך סנכרון ← אזור מסוכן.',
};

function translateDynamic(message: string) {
  const translateField = (field: string) => translateMessage(
    field ? `${field[0].toUpperCase()}${field.slice(1)}` : field,
    'he',
  );
  const patterns: [RegExp, (...parts: string[]) => string][] = [
    [/^(\d+) choices available$/, (count) => `${count} אפשרויות זמינות`],
    [/^(\d+) transactions$/, (count) => `${count} תנועות`],
    [/^(\d+) transaction$/, (count) => `תנועה אחת`],
    [/^(\d+) selected$/, (count) => `${count} נבחרו`],
    [/^Amount \((.+)\)$/, (currency) => `סכום (${currency})`],
    [/^Opening balance \((.+)\)$/, (currency) => `יתרת פתיחה (${currency})`],
    [/^Destination amount \((.+)\)$/, (currency) => `סכום יעד (${currency})`],
    [/^Target \((.+)\)$/, (currency) => `יעד (${currency})`],
    [/^(.+) \((.+)\)$/, (label, value) => `${translateField(label)} (${value})`],
    [/^Next (.+)$/, (date) => `הבא: ${date}`],
    [/^Effective (.+)$/, (date) => `בתוקף מ־${date}`],
    [/^No activity in (.+)$/, (month) => `אין פעילות ב${month}`],
    [/^Import (\d+) transactions$/, (count) => `ייבוא ${count} תנועות`],
    [/^Row (\d+): (.+)$/, (row, reason) => `שורה ${row}: ${translateMessage(reason, 'he')}`],
    [/^Use (#[0-9A-Fa-f]{6}) (.+)$/, (color, item) => `שימוש ב־${color} עבור ${translateMessage(item, 'he')}`],
    [/^Archived account · (.+)$/, (currency) => `חשבון בארכיון · ${currency}`],
    [/^Archived (.+) category$/, (kind) => `קטגוריית ${translateMessage(kind, 'he')} בארכיון`],
    [/^Every (\d+) (day|week|month|year)s?\.$/, (count, unit) => `כל ${count} ${translateMessage(unit, 'he')}`],
    [/^(\d+)% remains in this period\.$/, (percent) => `${percent}% נותרו בתקופה הזו.`],
    [/^(.+) is required\.$/, (label) => `יש למלא את השדה ${translateField(label)}.`],
    [/^(.+) must be greater than zero\.$/, (label) => `${translateField(label)} חייב להיות גדול מאפס.`],
    [/^(.+) cannot be negative\.$/, (label) => `${translateField(label)} אינו יכול להיות שלילי.`],
    [/^Enter a valid (.+)\.$/, (label) => `הזינו ${translateField(label)} תקין.`],
    [/^Use a real (.+) in YYYY-MM-DD format\.$/, (label) => `השתמשו ב${translateField(label)} אמיתי בתבנית YYYY-MM-DD.`],
    [/^(.+) must be a positive whole number\.$/, (label) => `${translateField(label)} חייב להיות מספר שלם וחיובי.`],
    [/^(.+) must be a whole number\.$/, (label) => `${translateField(label)} חייב להיות מספר שלם.`],
    [/^(.+) can have at most (\d+) decimal places\.$/, (label, digits) => `ל${translateField(label)} יכולות להיות לכל היותר ${digits} ספרות אחרי הנקודה.`],
    [/^(.+) is outside the supported range\.$/, (label) => `${translateField(label)} מחוץ לטווח הנתמך.`],
    [/^Choose a valid (expense|income) category\.$/, (kind) => `בחרו קטגוריית ${translateMessage(kind, 'he')} תקינה.`],
    [/^Choose a currency other than (.+)\.$/, (currency) => `בחרו מטבע אחר מ־${currency}.`],
    [/^Map (.+)$/, (field) => `מיפוי ${translateField(field)}`],
    [/^Choose valid (.+) values\.$/, (label) => `בחרו ערכי ${translateField(label)} תקינים.`],
    [/^Could not find the (.+) to update\.$/, (label) => `לא נמצאה רשומת ${translateField(label)} לעדכון.`],
    [/^(.+) is already in use\.$/, (name) => `השם ${name} כבר בשימוש.`],
    [/^Missing exchange rate for (.+) → (.+) on (.+)\.$/, (from, to, date) => `חסר שער חליפין מ־${from} ל־${to} בתאריך ${date}.`],
    [/^The (.+) category can only be assigned to (expense|income) transactions\.$/, (name, kind) => `ניתן לשייך את הקטגוריה ${name} רק לתנועות ${translateMessage(kind, 'he')}.`],
    [/^Currency (.+) does not match (.+) \((.+)\)\.$/, (currency, account, expected) => `המטבע ${currency} אינו תואם לחשבון ${account} (${expected}).`],
    [/^Unknown account: (.+)$/, (account) => `חשבון לא מוכר: ${account}`],
    [/^Unknown destination account: (.+)$/, (account) => `חשבון יעד לא מוכר: ${account}`],
    [/^Unknown category: (.+)$/, (category) => `קטגוריה לא מוכרת: ${category}`],
    [/^Unsupported currency or locale: (.+) \((.+)\)\.$/, (currency, locale) => `מטבע או הגדרת אזור אינם נתמכים: ${currency} (${locale}).`],
    [/^This contradicts the existing (.+) → (.+) rate of (.+), which implies (.+)\. Update or remove that rate first\.$/, (from, to, rate, implied) => `הערך סותר את השער הקיים מ־${from} ל־${to}, שערכו ${rate} ומשמעותו ${implied}. עדכנו או הסירו תחילה את השער הזה.`],
    [/^Archive (.+)\?$/, (name) => `להעביר את ${name} לארכיון?`],
    [/^Delete the (.+) rate\?$/, (currency) => `למחוק את שער ${currency}?`],
    [/^Delete (\d+) transactions\?$/, (count) => `למחוק ${count} תנועות?`],
    [/^Delete (.+)\?$/, (name) => `למחוק את ${name}?`],
    [/^“(.+)” will be removed from your ledger\.$/, (title) => `״${title}״ תוסר מהיומן.`],
    [/^(.+) from (\d{4}-\d{2}-\d{2}) will be removed from this goal\.$/, (amount, date) => `${amount} מתאריך ${date} יוסר מהיעד הזה.`],
    [/^(\d+) transactions imported\.$/, (count) => `יובאו ${count} תנועות.`],
    [/^Skipped (\d+) unreadable (row|rows)$/, (count) => `דולגו ${count} שורות שלא ניתן לקרוא`],
    [/^The rest of the file was read\. Check (?:line|lines) (.+) for stray quotes\.$/, (lines) => `שאר הקובץ נקרא. בדקו בשורות ${lines} אם יש מירכאות מיותרות.`],
    [/^Map required fields: (.+)\.$/, (fields) => `מפו את שדות החובה: ${fields}.`],
    [/^Malformed CSV quote on line (\d+)\.$/, (line) => `מירכאות CSV לא תקינות בשורה ${line}.`],
    [/^Unclosed quoted CSV field starting on line (\d+)\.$/, (line) => `שדה CSV במירכאות לא נסגר החל משורה ${line}.`],
    [/^1 (.+) equals how many (.+)\?$/, (from, to) => `לכמה ${to} שווה 1 ${from}?`],
    [/^Edit contribution (.+)$/, (amount) => `עריכת הפקדה ${amount}`],
    [/^Delete contribution (.+)$/, (amount) => `מחיקת הפקדה ${amount}`],

    // Sync. Singular and plural are separate entries rather than one pattern with a ternary:
    // Hebrew inflects the noun and the verb differently for one, and `1 device · just now`
    // reads as badly in Hebrew as "1 devices" does in English.
    //
    // Relative times first, because several of the composed shapes below re-enter
    // `translateMessage` with one as their tail.
    [/^1 minute ago$/, () => 'לפני דקה'],
    [/^(\d+) minutes ago$/, (count) => `לפני ${count} דקות`],
    [/^1 hour ago$/, () => 'לפני שעה'],
    [/^(\d+) hours ago$/, (count) => `לפני ${count} שעות`],
    [/^1 day ago$/, () => 'לפני יום'],
    [/^(\d+) days ago$/, (count) => `לפני ${count} ימים`],
    [/^1 month ago$/, () => 'לפני חודש'],
    [/^(\d+) months ago$/, (count) => `לפני ${count} חודשים`],
    // The vault size counts this device, so "1 device" is a real state, not an empty one.
    [/^1 device$/, () => 'מכשיר אחד'],
    [/^(\d+) devices$/, (count) => `${count} מכשירים`],
    [/^1 device · (.+)$/, (when) => `מכשיר אחד · ${translateMessage(when, 'he')}`],
    [/^(\d+) devices · (.+)$/, (count, when) => `${count} מכשירים · ${translateMessage(when, 'he')}`],
    [/^Direct only · 1 device$/, () => 'ישיר בלבד · מכשיר אחד'],
    [/^Direct only · (\d+) devices$/, (count) => `ישיר בלבד · ${count} מכשירים`],
    [/^Last exchanged changes (.+)\.$/, (when) => `שינויים הוחלפו לאחרונה ${translateMessage(when, 'he')}.`],
    [/^Last seen (.+)$/, (when) => `נראה לאחרונה ${translateMessage(when, 'he')}`],
    [/^Checked (.+)$/, (when) => `נבדק ${translateMessage(when, 'he')}`],
    [/^(\d+) changes need attention$/, (count) => `${count} שינויים דורשים תשומת לב`],
    [/^(.+) is still paired\.$/, (device) => `${device} עדיין מחובר.`],
    // Activity log. The counts are volumes, never content — see the note on the log itself.
    [/^Sent 1 change$/, () => 'נשלח שינוי אחד'],
    [/^Sent (\d+) changes$/, (count) => `נשלחו ${count} שינויים`],
    [/^Received 1 change$/, () => 'התקבל שינוי אחד'],
    [/^Received (\d+) changes$/, (count) => `התקבלו ${count} שינויים`],
    [/^Held back 1 change$/, () => 'שינוי אחד הוחזק'],
    [/^Held back (\d+) changes$/, (count) => `${count} שינויים הוחזקו`],
    [/^Applied 1 held-back change$/, () => 'הוחל שינוי אחד שהוחזק'],
    [/^Applied (\d+) held-back changes$/, (count) => `הוחלו ${count} שינויים שהוחזקו`],
    [/^Merged 1 duplicate$/, () => 'מוזגה כפילות אחת'],
    [/^Merged (\d+) duplicates$/, (count) => `מוזגו ${count} כפילויות`],
    [/^Cleared 1 old change$/, () => 'נוקה שינוי ישן אחד'],
    [/^Cleared (\d+) old changes$/, (count) => `נוקו ${count} שינויים ישנים`],
    // Pairing and recovery.
    [/^1 second left$/, () => 'נותרה שנייה אחת'],
    [/^(\d+) seconds left$/, (count) => `נותרו ${count} שניות`],
    [/^All (\d+) words, separated by spaces\.$/, (count) => `כל ${count} המילים, מופרדות ברווחים.`],
    // The word itself is passed through untouched — it comes from a fixed English wordlist
    // and must read identically on both devices for the comparison to mean anything.
    [/^Word (\d+): (.+)$/, (index, word) => `מילה ${index}: ${word}`],
    // Duplicate review.
    [/^Merged 1 record$/, () => 'מוזגה רשומה אחת'],
    [/^Merged (\d+) records$/, (count) => `מוזגו ${count} רשומות`],
    [/^1 record now points at the copy you kept\.$/, () => 'רשומה אחת מפנה כעת לעותק שהשארתם.'],
    [/^(\d+) records now point at the copy you kept\.$/, (count) => `${count} רשומות מפנות כעת לעותק שהשארתם.`],
    [/^Merge 1 group$/, () => 'מיזוג קבוצה אחת'],
    [/^Merge (\d+) groups$/, (count) => `מיזוג ${count} קבוצות`],
    [/^Keep this one, remove (\d+) copies$/, (count) => `להשאיר את זו ולהסיר ${count} עותקים`],
  ];
  for (const [pattern, replacement] of patterns) {
    const match = message.match(pattern);
    if (match) return replacement(...match.slice(1));
  }
  return message;
}

export function languageFromLocale(locale: string): AppLanguage {
  return locale.toLocaleLowerCase().startsWith('he') ? 'he' : 'en';
}

export function translateMessage(message: string, language: AppLanguage) {
  if (language === 'en' || !message) return message;
  const leading = message.match(/^\s*/)?.[0] ?? '';
  const trailing = message.match(/\s*$/)?.[0] ?? '';
  const core = message.slice(leading.length, message.length - trailing.length || undefined);
  // `hasOwn`, not a bare lookup: HEBREW is an object literal, so a message that
  // happens to name an Object.prototype member ("constructor", "toString", a
  // user-entered account called "valueOf") would resolve to the inherited function
  // and interpolate it into the UI. Nothing reaches this with free-form text today,
  // but the dictionary should not be able to answer for keys it does not hold.
  const translated = Object.hasOwn(HEBREW, core) ? HEBREW[core] : translateDynamic(core);
  return `${leading}${translated}${trailing}`;
}

type LocalizationValue = {
  language: AppLanguage;
  locale: string;
  isRtl: boolean;
  t: (message: string) => string;
};

const LocalizationContext = createContext<LocalizationValue | null>(null);
let currentLanguage: AppLanguage = 'en';

export function LocalizationProvider({ children }: { children: ReactNode }) {
  const { settings } = useFinanceState();
  const language = languageFromLocale(settings.locale);
  const value = useMemo<LocalizationValue>(() => ({
    language,
    locale: settings.locale,
    isRtl: language === 'he',
    t: (message) => translateMessage(message, language),
  }), [language, settings.locale]);
  useEffect(() => {
    currentLanguage = language;
    if (process.env.EXPO_OS === 'web' && typeof document !== 'undefined') {
      document.documentElement.lang = language === 'he' ? 'he-IL' : 'en-US';
      document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
    }
  }, [language]);
  return <LocalizationContext value={value}>{children}</LocalizationContext>;
}

export function translateCurrent(message: string) {
  return translateMessage(message, currentLanguage);
}

export function useLocalization() {
  const value = use(LocalizationContext);
  if (!value) throw new Error('useLocalization must be used inside LocalizationProvider.');
  return value;
}
